import { chromium } from '/root/proyectos/roblox-juego/node_modules/playwright/index.mjs';
const URL = process.env.URL || 'http://127.0.0.1:8799/';
const W = 900, H = 520;
const paso = (m) => console.log('  ..', m, new Date().toISOString().slice(11,19));
const b = await chromium.launch({ args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: W, height: H } });
const errs = [], diag = [];
p.on('pageerror', e => errs.push(String(e).slice(0,160)));
p.on('console', m => { const t = m.text(); if (/orden|Tuberia|tuberia|Emisores/i.test(t)) diag.push(t); });
const toca = async (fx, fy, ms=1400) => { await p.mouse.click(W*fx, H*fy); await p.waitForTimeout(ms); };
paso('goto'); await p.goto(URL + '?diag', { waitUntil: 'load' });
await p.waitForTimeout(26000); paso('cargado');
await toca(0.5,0.92); await toca(0.33,0.64); await toca(0.5,0.81);
await p.waitForTimeout(6000); paso('menus');
await toca(0.5,0.5); await toca(0.5,0.5); paso('en juego');
const cuadrosA = await p.evaluate(() => window.__pdDiag && window.__pdDiag.cuadros);
await p.evaluate(() => { window.__pdOrden = 'alLadoDeUnaTuberia'; });
await p.waitForTimeout(3500); paso('orden dada');
const cuadrosB = await p.evaluate(() => window.__pdDiag && window.__pdDiag.cuadros);
console.log('  cuadros antes/despues:', cuadrosA, cuadrosB);
await p.evaluate(() => { window.__pdOrden = 'verTuberia'; });
await p.waitForTimeout(1500);
await p.screenshot({ path: process.env.OUT }); paso('captura');
console.log('diag    :', diag.slice(-2).join(' | '));
console.log('errores :', errs.length, errs.slice(0,3).join(' // '));
await b.close();
